contents:
  status:
  - description: foo
    icon: healthy
    id: 1
  - description: bar
    icon: warning
    id: 2
schema:
  status:
  - name: description
    required: true
    type: text
  - choices:
    - healthy
    - warning
    - failed
    - pending
    name: icon
    type: choice
