schema:
  status:
    - name: description
      type: text
      required: True
    - name: icon
      type: choice
      choices:
        - healthy
        - warning
        - failed
        - pending
contents:
