contents: []
schema:
  note:
  - name: bug
    type: integer
  - name: note
    type: text
  - choices:
    - fixed
    - developer
    - language
    name: tag
    type: choice
  release:
  - autoincrement: true
    display: false
    name: id
    type: integer
  - label: Product
    name: product
    placeholder: Firefox
    type: string
  - choices:
    - Release
    - Beta
    - Aurora
    - Nightly
    - ESR
    label: Channel
    name: channel
    type: choice
  - name: version
    type: string
  - name: release_date
    type: date
  - name: text
    type: text
  - name: is_public
    type: boolean
  - label: Bug search URL
    name: bug_search_url
    type: url
  - name: system_requirements
    type: text
  - list_type: note
    name: notes
    type: list
