schema:
  release:
    - name: id
      type: integer
      autoincrement: true
      display: false
    - name: product
      type: string
      label: Product
      placeholder: Firefox
    - name: channel
      type: choice
      label: Channel
      choices:
        - Release
        - Beta
        - Aurora
        - Nightly
        - ESR
    - name: version
      type: string
    - name: release_date
      type: date
    - name: text
      type: text
    - name: is_public
      type: boolean
    - name: bug_search_url
      type: url
      label: Bug search URL
    - name: system_requirements
      type: text
    - name: notes
      type: list
      list_type: note
  note:
    - name: bug
      type: integer
    - name: note
      type: text
    - name: tag
      type: choice
      choices:
        - fixed
        - developer
        - language
contents:
